version: '3.8'

services:
    # NestJS
    nestdev:
        container_name: studies-nestjs
        image: nestjs-api-dev:1.0.0
        env_file:
            - .env
        build:
            context: .
            target: local
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - ${APP_PORT}:${APP_PORT}
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        depends_on:
            - nestmysql
        links:
            - nestmysql

    # DB - MySQL 5.7
    nestmysql:
        container_name: studies-mysql
        image: mysql:5.7
        platform: linux/x86_64
        env_file:
            - .env
        environment:
            MYSQL_PORT: ${DB_MYSQL_PORT}
            MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASS}
            MYSQL_DATABASE: ${DB_MYSQL_NAME}
            MYSQL_USER: ${DB_MYSQL_USER}
            MYSQL_PASSWORD: ${DB_MYSQL_PASS}
        command:
            - --explicit_defaults_for_timestamp
            - --default-authentication-plugin=mysql_native_password
        volumes:
            - nest-mysql-volume:/var/lib/mysql
            - ./docker/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
        ports:
            - "${DB_MYSQL_PORT}:${DB_MYSQL_PORT}"
        networks:
            - nesjs-network
        restart: always

volumes:
    nest-mysql-volume:

networks:
    nesjs-network: