version: '3.8'

services:
    # NestJS
    dev:
        container_name: studies-nestjs
        image: nestjs-api-dev:1.0.0
        env_file:
            - .env
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - ${APP_PORT}:${APP_PORT}
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        depends_on:
            - mongo
        links:
            - mongo

    # MongoDB
    mongo:
        container_name: studies-mongodb
        image: mongo:latest
        env_file:
            - .env
        environment:
            MONGO_INITDB_DATABASE: ${DB_MONGO_NAME}
            MONGO_INITDB_USERNAME: root
            MONGO_INITDB_PASSWORD: pass
            MONGO_USER: ${DB_MONGO_USER}
            MONGO_PASS: ${DB_MONGO_PASS}
        volumes:
            - dbdata-volume:/data/db
            - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        ports:
            - ${DB_MONGO_PORT}:27017
        networks:
            - nesjs-network
        restart: always

volumes:
    dbdata-volume:

networks:
    nesjs-network: